language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: 7

env:
  - SUITE=comodojo-cache-travis

services:
  - memcached
  - redis-server

before_install:
  - sudo apt-get update -qq
  - if [[ "$TRAVIS_PHP_VERSION" == 5.3* ]] ; then echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; fi
  - if [[ "`phpenv version-name`" != "hhvm" && "$TRAVIS_PHP_VERSION" != 5.3* ]] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu ; fi
  - if [[ "`phpenv version-name`" != "hhvm" ]] ; then phpenv config-add $TRAVIS_BUILD_DIR/tests/resources/ext.ini ; fi
  - travis_retry composer self-update
  - mysql -u root < $TRAVIS_BUILD_DIR/tests/resources/DatabaseCacheCreateSchema.sql

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit --testsuite $SUITE; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --testsuite $SUITE --coverage-text --coverage-clover=coverage.clover; fi

after_script:
  - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != "hhvm" && "$TRAVIS_PHP_VERSION" != "7.0" ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi;'
