language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

services:
  - memcached
  - redis-server

before_install:
  - sudo apt-get update -qq
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]] ; then phpenv config-add $TRAVIS_BUILD_DIR/tests/resources/ext.ini ; fi
  - if [[ $TRAVIS_PHP_VERSION = 5.4 ]] ; then echo 'extension=apcu.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then pecl channel-update pecl.php.net; fi;
  - if [[ $TRAVIS_PHP_VERSION =~ 5.[456] ]] ; then echo yes | pecl install apcu-4.0.10; fi;
  - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then pecl config-set preferred_state beta; echo yes | pecl install apcu; fi;
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi

after_script:
  - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi;'
