language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: 7
    - php: hhvm

env:
  - SUITE=comodojo-cache-travis

services:
  - memcached
  - redis-server

before_install:
  - sudo apt-get update -qq
  - mysql -u root < $TRAVIS_BUILD_DIR/tests/resources/DatabaseCacheCreateSchema.sql

before_script:
  - composer install --prefer-source
  - phpenv config-add $TRAVIS_BUILD_DIR/tests/resources/ext.ini

script: ./vendor/bin/phpunit --testsuite $SUITE
